"""empty message

Revision ID: 1124b280e25d
Revises: f5e7b325ba85
Create Date: 2024-06-21 12:52:47.174118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1124b280e25d'
down_revision = 'f5e7b325ba85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido_paterno', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('apellido_materno', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('apellido_materno')
        batch_op.drop_column('apellido_paterno')

    # ### end Alembic commands ###
