"""empty message

Revision ID: 65991b0654eb
Revises: 
Create Date: 2024-06-21 10:30:00.834431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65991b0654eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('carrera', sa.String(), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('sub_total', sa.Integer(), nullable=False),
    sa.Column('notas', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('carrera', sa.String(), nullable=False),
    sa.Column('imagen_producto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('carrera', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rol', sa.String(length=255), nullable=False))
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('role')
        batch_op.drop_column('name')
        batch_op.drop_column('career')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('rol')
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('carrera')
        batch_op.drop_column('nombre')

    op.drop_table('producto')
    op.drop_table('pedido')
    op.drop_table('admin')
    # ### end Alembic commands ###
