"""empty message

Revision ID: 6a12abb78e59
Revises: 6cb4f3defad5
Create Date: 2024-08-16 06:56:20.865074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a12abb78e59'
down_revision = '6cb4f3defad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('ubicacion')

    with op.batch_alter_table('pedido_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_producto', schema=None) as batch_op:
        batch_op.drop_column('ubicacion')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
