"""empty message

Revision ID: 6cb4f3defad5
Revises: 3fd8d8fed533
Create Date: 2024-08-16 04:06:58.616272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb4f3defad5'
down_revision = '3fd8d8fed533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrera', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_producto', schema=None) as batch_op:
        batch_op.drop_column('carrera')

    # ### end Alembic commands ###
