"""empty message

Revision ID: b2893c9c9337
Revises: 6a12abb78e59
Create Date: 2024-08-16 09:26:41.883479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2893c9c9337'
down_revision = '6a12abb78e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrera', sa.String(length=150), nullable=True))

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('fecha_recibido')
        batch_op.drop_column('fecha_limite')

    with op.batch_alter_table('pedido_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fecha_recibido', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_limite', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_producto', schema=None) as batch_op:
        batch_op.drop_column('fecha_limite')
        batch_op.drop_column('fecha_recibido')
        batch_op.drop_column('estatus')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_limite', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('fecha_recibido', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.drop_column('carrera')

    # ### end Alembic commands ###
