"""empty message

Revision ID: bc0f6ece4d00
Revises: c5b25c757eed
Create Date: 2024-09-20 08:47:40.672749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0f6ece4d00'
down_revision = 'c5b25c757eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encoding', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encoding', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.drop_column('encoding')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('encoding')

    # ### end Alembic commands ###
