"""empty message

Revision ID: c5b25c757eed
Revises: b2893c9c9337
Create Date: 2024-09-06 03:35:40.249285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b25c757eed'
down_revision = 'b2893c9c9337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('id_usuario_cierre')

    with op.batch_alter_table('pedido_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario_cierre', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_producto', schema=None) as batch_op:
        batch_op.drop_column('id_usuario_cierre')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario_cierre', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
