"""empty message

Revision ID: f5e7b325ba85
Revises: 6e2971d4caea
Create Date: 2024-06-21 11:07:32.057200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e7b325ba85'
down_revision = '6e2971d4caea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
